### ISSUE TITLE
Unable to create ticket: No input file specified.

### ISSUE THREAD

**Issue by de4niih** [LiveHelperChat/osTicket#1]
First of all thank you very much for providing this awesome Live Chat tool. Its really great.

Now I was about to setup the osTicket extension but I'm getting "Unable to create ticket: No input file specified." error when I click on "Create a ticket" in LHC.
![new-blank](https://cloud.githubusercontent.com/assets/11258944/7708094/cbdc8cf6-fe53-11e4-838a-ddaac819829a.png)

Please see the attached Screenshots for more details.

![scr_2015-05-19_17-57-55](https://cloud.githubusercontent.com/assets/11258944/7708081/b64bf1d8-fe53-11e4-8c52-1c1f76b35a00.png)

![bildschirmfoto vom 2015-05-19 17 45 55](https://cloud.githubusercontent.com/assets/11258944/7708088/bee3f9e4-fe53-11e4-9933-42eb6755b06a.png)

![bildschirmfoto vom 2015-05-19 17 44 38](https://cloud.githubusercontent.com/assets/11258944/7708090/c3a06634-fe53-11e4-9e8b-1e2d94d323be.png)

Please let me know if you need some further details.

**Comment by remdex** [comment]
Sorry but all works here.
https://livehelperchat.com/godaddy-configuration-tutorial-avoiding-no-input-file-specified-error-119a.html

**Comment by de4niih** [comment]
@remdex thank you very much. This, and another tweak did the trick for me.
I had to change my PHP from FastCGI to CGI only, add these values to 
![scr_2015-05-19_21-30-37](https://cloud.githubusercontent.com/assets/11258944/7711973/83358f64-fe6e-11e4-8e79-778768967375.png)

.htaccess and the php.ini and since then its working GREAT.

Thanks a lot again for your support.
