### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by shahmirf** [LiveHelperChat/osTicket#12]
Greetings
When created Ticket from Live Help Chat to osTicket the Unicode convert in to garbage characters as following, is there any solution to fix this issue?

Chat ID - 39<br /> User nick - test11, //---------------//<br /> ---------------//<br /> <br /> //---------------//<br /> Chat log<br /> 2020-02-27 10:05:52 test01: Ø±Ø³Ø§ÙØ Ø§ÙØ§ØØØ¨Ø§Ø± # 001<br /> 2020-02-27 10:06:29 Support: Ø¥ØµØ¯Ø§Ø± Ø§ÙØ±Ø¯ # 001<br /> <br /> <br /> //---------------//<br /> Operator remarks<br />

**Comment by remdex** [comment]
LHC Internally always stores information in UTF.

This is the part where all happens.
https://github.com/LiveHelperChat/osTicket/blob/master/osticket/bootstrap/bootstrap.php#L60

So please check your osTicket configuration/LHC Configuration. Because someone is missing UTF headers.
