### ISSUE TITLE
Unable to create ticket : valid api key required

### ISSUE THREAD

**Issue by damaragung** [LiveHelperChat/osTicket#3]
Hi,, thanks for the osTicket plugin you've made. 
but i get this error when click create ticket "Unable to create ticket : valid api key required"  . 
i already insert the right api. attached is the screenshot.

![osticket-livehelperchat-error](https://cloud.githubusercontent.com/assets/6584634/10014659/1217b8ea-6145-11e5-802c-9e78eeb196cd.jpg)

btw, i changed this part 
'host' => 'localhost/getcraft/helpdesk/api/http.php/tickets.json', 

if i didn't add " http.php " , error message below will appear
![osticket-livehelperchat-error-2](https://cloud.githubusercontent.com/assets/6584634/10014733/832a5344-6145-11e5-8ae0-7402dd393f61.jpg)

thanks

**Comment by damaragung** [comment]
Ok,, then i try to create new API Key in osTicket . I input ip address " ::1 "  (btw, i testing it in localhost environment)  . It works ! the API Key is valid,, but I got another error message 
![osticket-livehelperchat-error-3](https://cloud.githubusercontent.com/assets/6584634/10015347/d5850a90-6149-11e5-89ad-558d15ef2855.jpg)

**Comment by damaragung** [comment]
I modify email field as required. now works perfectly. thanks for your plugin. great works
![start chat form settings system configuration live helper chat live support](https://cloud.githubusercontent.com/assets/6584634/10016536/e7957aaa-6151-11e5-9b13-2e83160388ac.png)

**Comment by SAPHemlock** [comment]
> Ok,, then i try to create new API Key in osTicket . I input ip address " ::1 " (btw, i testing it in localhost environment) . It works ! the API Key is valid,, but I got another error message
> ![osticket-livehelperchat-error-3](https://cloud.githubusercontent.com/assets/6584634/10015347/d5850a90-6149-11e5-89ad-558d15ef2855.jpg)

This bug is still present in 1.12.3 in 2019 and your suggestion worked! Thnx.
