### ISSUE TITLE
Unable to enable selected API key.

### ISSUE THREAD

**Issue by austin1210** [LiveHelperChat/osTicket#4]
Hi,, thanks for the osTicket plugin you've made. 
But i get this error when select API Key and click Enable button.
I already insert the right api. attached is the screenshot.

![1](https://cloud.githubusercontent.com/assets/16329719/11859409/68b377c2-a4a5-11e5-8c73-f8673bb27f8d.jpg)
![2](https://cloud.githubusercontent.com/assets/16329719/11859411/6bc8b044-a4a5-11e5-8c51-7e1a84eb7624.jpg)

**Comment by anmolgupta** [comment]
Same issue with me

**Comment by remdex** [comment]
Please update extension. Configuration has to be done using back office. You have to enter 'extensions' => array(0 => 'osticket') in settings/settings.ini.php file
