### ISSUE TITLE
3rd-party ticket system integration "Create ticket" button

### ISSUE THREAD

**Issue by sabatale** [LiveHelperChat/osTicket#9]
Hello,

It's really more of a question but I'll give it a shot! Is there any procedure or hints on how to create a ticket in a 3rd-party tool out of a conversation chat? I understand there is the REST API but I'm not sure where to look at as to where the agent can actually submit a ticket. I was thinking of looking into the osTicket plugin and maybe adapt it, but I'm wondering if this is actually a good place to start?

Thanks!

**Comment by remdex** [comment]
Hi,

Yes. osTicket is the best thing you can reuse :)

**Comment by sabatale** [comment]
Thanks for your quick answer! I was asking because whenever I enable the standard osTicket extension, chats are not working anymore (clicking Submit from the user perspective triggers a 503 error). All is working fine without the extension - would you know if this is a known issue?
